GET https://api.cobinhood.com/v1/system/time HTTP/1.1
###
GET https://api.binance.com/api/v1/time HTTP/1.1
###
GET https://api.binance.com/api/v1/exchangeInfo HTTP/1.1
###
GET https://api.cobinhood.com/v1/system/info  HTTP/1.1
### orderbooks
GET https://api.binance.com/api/v1/depth?symbol=ETHBTC HTTP/1.1
### traiding pairs
GET https://api.cobinhood.com/v1/market/trading_pairs HTTP/1.1
### orderbooks
GET https://api.cobinhood.com/v1/market/orderbooks/ETH-USD HTTP/1.1
### candles
GET https://api.binance.com/api/v1/klines?interval=5m&symbol=ETHBTC HTTP/1.1
### candles
GET https://api.cobinhood.com/v1/chart/candles/INS-ETH HTTP/1.1
### aggtrades
GET https://api.binance.com/api/v1/aggTrades?symbol=ETHBTC HTTP/1.1
### trades
GET https://api.binance.com/api/v1/trades?symbol=ETHBTC HTTP/1.1
### trades
GET https://api.cobinhood.com/v1/market/trades/ETH-USD HTTP/1.1
### all tickers
GET https://api.binance.com/api/v1/ticker/allBookTickers HTTP/1.1
### Get Trading Statistics
GET https://api.cobinhood.com/v1/market/stats HTTP/1.1
